

version: "3.9"


services:
  web:
    build:
      context: ./volumes/build/php74
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./volumes/src:/var/www/html
      - ./volumes/etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
